name: tfsec
on: [pull_request]

jobs:
  ubuntu:
    name: tfsec / ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: tfsec
        uses: reviewdog/action-tfsec@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          reporter: "github-pr-check"
          working_directory: "."
          filter_mode: "nofilter"
          level: "info"
